### ISSUE TITLE
Budget error on unique skills

### ISSUE THREAD

**Issue by MZamero** [cecilbowen/qurios-crafting-simulator#1]
On the Webpage adding the exclusive skill on the original armor "Dragonheart", "Bloodlust", etc. adds "-1" to the budget used

Example
Valstrax Braces - Eclipse,0,0,0,0,0,0,0,0,0,Dragonheart,4,,,,,,
![image](https://user-images.githubusercontent.com/50846803/188705877-6c8ee63c-1062-4521-9945-977734fe060a.png)

**Comment by cecilbowen** [comment]
This occurred because non-augmentable skills (skills that were not in the list of possible skills to be rolled), were previously allowed to be increased/decreased in the sim.  The skills have now been locked from editing, similar in functionality to how skills on the Narwa/Ibushi sets cannot be edited (clicking the +/- symbols does nothing).

For a full list of non-augmentable skills, you can reference `skills_all.json` where the skills with `augmentable` set to `false` are not augmentable.
